### ISSUE TITLE
Adding stuff to Electron core

### ISSUE THREAD

**Issue by zeke** [sindresorhus/electron-util#6]
This module has some pretty handy tricks that would be generally useful for all Electron apps.

@sindresorhus did you attempt to land any of this stuff in Electron core?

If so, why didn't it work out? If not, why not?

**Comment by sindresorhus** [comment]
Which methods did you have in mind?

This is what I've done:

- Got `.appReady()` added as `app.whenReady()` to Electron. https://github.com/electron/electron/pull/12652
- Got `.loadFile()` included in Electron. https://github.com/electron/electron/commit/1553b547792b2e28c11b7498d0fc705445d0184f
- The `.menuBarHeight()` was removed from Electron. I added it here because I find this more readable than the alternative. See: https://github.com/electron/electron/pull/12135
- The `.centerWindow()` method, is like the `BrowserWindow.center()` method, but it has an `animated` option. I've opened an issue about this here: https://github.com/electron/electron/issues/12176
- The `.disableZoom()` method will be made partly moot by https://github.com/electron/electron/pull/12679

I'm not sure I want to open any more issues though, as Electron is currently an unstable mess and I would prefer the core team to focus on fixing bugs and improving performance instead of adding new features.

**Comment by zeke** [comment]
I didn't have anything specific in mind. Just curious to know about your experience creating this module and interacting with the Electron core team.

> Electron is currently an unstable mess

It has been a tumultuous few months, but I think it's stabilizing as the team improves the Chromium upgrade process and settles into a flow of semantic releases. Also, nightly releases are in the works. Hopefully we can start plucking more good ideas from this module in the future.

**Comment by sindresorhus** [comment]
I'll open some feature requests for APIs I think should be in core when I find some time.
